const ShopActionTypes = {
  FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
  FETCH_COLLECTION_SUCCES: 'FETCH_COLLECTION_SUCCES',
  FETCH_COLLECTION_FAILURE: 'FETCH_COLLECTION_FAILURE',
};

export default ShopActionTypes;
